### ISSUE TITLE
Character input failed on `Submit`

### ISSUE THREAD

**Issue by OluwaninsolaAO** [Dare649/character-app#2]
## Character input failed on `Submit`

Hello there @Dare649, kindly look into this, I think you must have missed something when handling the form submission for your `First Screen`, the submission wouldn't go through. Check the attached image below as a reference:

![image](https://github.com/Dare649/character-app/assets/36889745/b8de334e-a05b-4995-86ba-15e8e96608cf)

> Feel free to close this issue once there is a fix available.

**Comment by OluwaninsolaAO** [comment]
@Dare649

> Also, you should know that it might be beneficial to include instructions for setting up your project on another machine. I noticed that your project uses `Axios` for API calls and has a dependency on `json-server`. Although the guidelines don't explicitly prohibit network requests, providing documentation on how to run your application would be more helpful.

**Comment by Dare649** [comment]
@OluwaninsolaAO thank you for your comment. I'd check and revert as I was able to create a couple of character to test the project before submitting.

**Comment by Dare649** [comment]
@OluwaninsolaAO Please I'd like to ask if the json-server was running while the test was done.

**Comment by OluwaninsolaAO** [comment]
@Dare649 
Yes, I do. I believe maybe there are additional steps involved in getting the json-server ready for your use case, just document your process and how to reproduce.

**Comment by Dare649** [comment]
@OluwaninsolaAO Alright, will document and let you know once I'm done, thank you I really appreciate your feedback.

**Comment by Dare649** [comment]
@OluwaninsolaAO I've added a README.md file and also kept comments in the code base to assist with the flow. I also tested to confirm it's fine of which it did work, luching thr json-server with npx json-server -p 3000 -w data/db.json

Thank you very much, I really appreciate. I look forward to your feedback on the code.

**Comment by Dare649** [comment]
Hi @OluwaninsolaAO trust you're doing great.  I wanted to follow-up on the code review, I'd appreciate your feedback, thank you.

**Comment by OluwaninsolaAO** [comment]
Hello there @Dare649, I have been able to check your submission result and code structure.

While you've demonstrated excellent skills with React and TailwindCSS, adding a creative flair to your work, the output on screen 2 does not keenly follow the provided instructions. To clarify:

- [x] It displays the original string entered by the user, `with each character represented as a
card` on the UI.
- [x] `Each card` should include `the character` and a delete icon.
- [x] `Clicking on the card should remove all duplicate instances of the chosen character from
the string`, leaving only the clicked instance on the screen.
- [x] Cards representing the same characters should have the same background colour.
- [x] If there are no more characters with more than one appearance in the string, a success
message should be displayed with both the original and resulting strings.

Please check and revert once the changes have been implemented. Looking forward to hearing back from you.

**Comment by Dare649** [comment]
Hi @OluwaninsolaAO thank you for taking out time with your feedbacks as regards the task, I really appreciate and can't wait to be part of the team to enjoy mentorship from someone like you. I've update the code in alignment with the requirements. I look forward to your quick feedback as always, thank you.

**Comment by OluwaninsolaAO** [comment]
Hi there @Dare649 

Great attempt, I see you have made all necessary adjustments to match the requirements. However, I believe there are still some minor technical issues you'd need to tend to. Ensure that you properly test your app for all scenarios you can imagine and make sure your app works as expected.

While testing your app, I noticed it got stuck without actually completing the task, see the screen below as a reference:

![image](https://github.com/Dare649/character-app/assets/36889745/e44b8e88-af78-4d63-a1f9-6a05f1c9c3bd)

The cards -- at this point, no longer respond to on-click events, and as you can see there are still a couple of duplicate characters to get rid of.

Look into this as soon as you can. Good job. Cheers.

**Comment by Dare649** [comment]
@OluwaninsolaAO thank you for your feedback. So I just tested now and the onClick works in deleting the duplicates, heres a screenshot.
![Screenshot (259)](https://github.com/Dare649/character-app/assets/121406237/03279b76-90f0-408f-aa4f-10237a55699b)
![Screenshot (260)](https://github.com/Dare649/character-app/assets/121406237/7039c43f-b077-4c37-b6ae-3ae94eb50ef7)

**Comment by Dare649** [comment]
@OluwaninsolaAO upon successful removal of the duplicates I got the result string.

**Comment by OluwaninsolaAO** [comment]
Try with this string `aasscsccdcrcddcd` and share your result.

**Comment by Dare649** [comment]
yeah, i just tried that scenario it failed, i'm working on it at the moment, will revert, thank you.

**Comment by Dare649** [comment]
@OluwaninsolaAO I'm done sir, the scenario now works, I look forward to your feedback, thank you.

**Comment by Dare649** [comment]
Hi @OluwaninsolaAO trust your day is going well. I didn't get any feedback from you, so I thought to chat you. I look forward to reading from you, thank you.

**Comment by OluwaninsolaAO** [comment]
@Dare649 Thanks for the reminder, sorry it's been a hectic day.

Great job so far. You did everything right this time, only a tiny bit of something missing. The `original string` was not what was expected on the success message. 

![image](https://github.com/Dare649/character-app/assets/36889745/ca9f2ffb-5d9c-4ee2-a38a-25f365fc3802)

**Comment by Dare649** [comment]
Okay sir, I'd adjust it and revert, thank you.

**Comment by Dare649** [comment]
Hi @OluwaninsolaAO , trust you are doing great. The issue as been fixed sir. I really want to appreciate you for your guide during on this task I really appreciate, looking forward to being mentored by you.

**Comment by OluwaninsolaAO** [comment]
@Dare649 

Excellent job, I have checked it. You did met all the task requirements.
